// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/EventService.proto

package pb

import (
	duration "github.com/golang/protobuf/ptypes/duration"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventCreateRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Event         *EventCreateRequest_Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCreateRequest) Reset() {
	*x = EventCreateRequest{}
	mi := &file_api_EventService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCreateRequest) ProtoMessage() {}

func (x *EventCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCreateRequest.ProtoReflect.Descriptor instead.
func (*EventCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{0}
}

func (x *EventCreateRequest) GetEvent() *EventCreateRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type EventCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCreateResponse) Reset() {
	*x = EventCreateResponse{}
	mi := &file_api_EventService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCreateResponse) ProtoMessage() {}

func (x *EventCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCreateResponse.ProtoReflect.Descriptor instead.
func (*EventCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{1}
}

func (x *EventCreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EventUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the event to update
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // ISO 8601 format
	Duration      *duration.Duration     `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Notification  int32                  `protobuf:"varint,6,opt,name=notification,proto3" json:"notification,omitempty"` // in hours
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventUpdateRequest) Reset() {
	*x = EventUpdateRequest{}
	mi := &file_api_EventService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUpdateRequest) ProtoMessage() {}

func (x *EventUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventUpdateRequest.ProtoReflect.Descriptor instead.
func (*EventUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{2}
}

func (x *EventUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventUpdateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventUpdateRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *EventUpdateRequest) GetDuration() *duration.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *EventUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventUpdateRequest) GetNotification() int32 {
	if x != nil {
		return x.Notification
	}
	return 0
}

type EventUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventUpdateResponse) Reset() {
	*x = EventUpdateResponse{}
	mi := &file_api_EventService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUpdateResponse) ProtoMessage() {}

func (x *EventUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventUpdateResponse.ProtoReflect.Descriptor instead.
func (*EventUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{3}
}

func (x *EventUpdateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EventRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ID of the event to remove
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRemoveRequest) Reset() {
	*x = EventRemoveRequest{}
	mi := &file_api_EventService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRemoveRequest) ProtoMessage() {}

func (x *EventRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRemoveRequest.ProtoReflect.Descriptor instead.
func (*EventRemoveRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{4}
}

func (x *EventRemoveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EventRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRemoveResponse) Reset() {
	*x = EventRemoveResponse{}
	mi := &file_api_EventService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRemoveResponse) ProtoMessage() {}

func (x *EventRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRemoveResponse.ProtoReflect.Descriptor instead.
func (*EventRemoveResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{5}
}

func (x *EventRemoveResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EventWeekListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`                            // User ID to filter events
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // Start date of the week in ISO 8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventWeekListRequest) Reset() {
	*x = EventWeekListRequest{}
	mi := &file_api_EventService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventWeekListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventWeekListRequest) ProtoMessage() {}

func (x *EventWeekListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventWeekListRequest.ProtoReflect.Descriptor instead.
func (*EventWeekListRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{6}
}

func (x *EventWeekListRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *EventWeekListRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

type EventWeekListResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Events        []*EventCreateRequest_Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"` // List of events
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventWeekListResponse) Reset() {
	*x = EventWeekListResponse{}
	mi := &file_api_EventService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventWeekListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventWeekListResponse) ProtoMessage() {}

func (x *EventWeekListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventWeekListResponse.ProtoReflect.Descriptor instead.
func (*EventWeekListResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{7}
}

func (x *EventWeekListResponse) GetEvents() []*EventCreateRequest_Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type EventMonthListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`                            // User ID to filter events
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // Start date of the month in ISO 8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMonthListRequest) Reset() {
	*x = EventMonthListRequest{}
	mi := &file_api_EventService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMonthListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMonthListRequest) ProtoMessage() {}

func (x *EventMonthListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMonthListRequest.ProtoReflect.Descriptor instead.
func (*EventMonthListRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{8}
}

func (x *EventMonthListRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *EventMonthListRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

type EventMonthListResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Events        []*EventCreateRequest_Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"` // List of events
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMonthListResponse) Reset() {
	*x = EventMonthListResponse{}
	mi := &file_api_EventService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMonthListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMonthListResponse) ProtoMessage() {}

func (x *EventMonthListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMonthListResponse.ProtoReflect.Descriptor instead.
func (*EventMonthListResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{9}
}

func (x *EventMonthListResponse) GetEvents() []*EventCreateRequest_Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type EventCreateRequest_Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // ISO 8601 format (e.g., "2023-10-01")
	Duration      *duration.Duration     `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	User          string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Notification  int32                  `protobuf:"varint,6,opt,name=notification,proto3" json:"notification,omitempty"` // in hours
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCreateRequest_Event) Reset() {
	*x = EventCreateRequest_Event{}
	mi := &file_api_EventService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCreateRequest_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCreateRequest_Event) ProtoMessage() {}

func (x *EventCreateRequest_Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCreateRequest_Event.ProtoReflect.Descriptor instead.
func (*EventCreateRequest_Event) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{0, 0}
}

func (x *EventCreateRequest_Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventCreateRequest_Event) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *EventCreateRequest_Event) GetDuration() *duration.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *EventCreateRequest_Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventCreateRequest_Event) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *EventCreateRequest_Event) GetNotification() int32 {
	if x != nil {
		return x.Notification
	}
	return 0
}

var File_api_EventService_proto protoreflect.FileDescriptor

const file_api_EventService_proto_rawDesc = "" +
	"\n" +
	"\x16api/EventService.proto\x12\x06events\x1a\x1egoogle/protobuf/duration.proto\"\x91\x02\n" +
	"\x12EventCreateRequest\x126\n" +
	"\x05event\x18\x01 \x01(\v2 .events.EventCreateRequest.EventR\x05event\x1a\xc2\x01\n" +
	"\x05Event\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12\"\n" +
	"\fnotification\x18\x06 \x01(\x05R\fnotification\"%\n" +
	"\x13EventCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcb\x01\n" +
	"\x12EventUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\fnotification\x18\x06 \x01(\x05R\fnotification\"%\n" +
	"\x13EventUpdateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12EventRemoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13EventRemoveResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x14EventWeekListRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\"Q\n" +
	"\x15EventWeekListResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .events.EventCreateRequest.EventR\x06events\"J\n" +
	"\x15EventMonthListRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\"R\n" +
	"\x16EventMonthListResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .events.EventCreateRequest.EventR\x06events2\x89\x03\n" +
	"\x06Events\x12H\n" +
	"\vEventCreate\x12\x1a.events.EventCreateRequest\x1a\x1b.events.EventCreateResponse\"\x00\x12H\n" +
	"\vEventUpdate\x12\x1a.events.EventUpdateRequest\x1a\x1b.events.EventUpdateResponse\"\x00\x12H\n" +
	"\vEventRemove\x12\x1a.events.EventRemoveRequest\x1a\x1b.events.EventRemoveResponse\"\x00\x12N\n" +
	"\rEventWeekList\x12\x1c.events.EventWeekListRequest\x1a\x1d.events.EventWeekListResponse\"\x00\x12Q\n" +
	"\x0eEventMonthList\x12\x1d.events.EventMonthListRequest\x1a\x1e.events.EventMonthListResponse\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_api_EventService_proto_rawDescOnce sync.Once
	file_api_EventService_proto_rawDescData []byte
)

func file_api_EventService_proto_rawDescGZIP() []byte {
	file_api_EventService_proto_rawDescOnce.Do(func() {
		file_api_EventService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_EventService_proto_rawDesc), len(file_api_EventService_proto_rawDesc)))
	})
	return file_api_EventService_proto_rawDescData
}

var file_api_EventService_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_EventService_proto_goTypes = []any{
	(*EventCreateRequest)(nil),       // 0: events.EventCreateRequest
	(*EventCreateResponse)(nil),      // 1: events.EventCreateResponse
	(*EventUpdateRequest)(nil),       // 2: events.EventUpdateRequest
	(*EventUpdateResponse)(nil),      // 3: events.EventUpdateResponse
	(*EventRemoveRequest)(nil),       // 4: events.EventRemoveRequest
	(*EventRemoveResponse)(nil),      // 5: events.EventRemoveResponse
	(*EventWeekListRequest)(nil),     // 6: events.EventWeekListRequest
	(*EventWeekListResponse)(nil),    // 7: events.EventWeekListResponse
	(*EventMonthListRequest)(nil),    // 8: events.EventMonthListRequest
	(*EventMonthListResponse)(nil),   // 9: events.EventMonthListResponse
	(*EventCreateRequest_Event)(nil), // 10: events.EventCreateRequest.Event
	(*duration.Duration)(nil),        // 11: google.protobuf.Duration
}
var file_api_EventService_proto_depIdxs = []int32{
	10, // 0: events.EventCreateRequest.event:type_name -> events.EventCreateRequest.Event
	11, // 1: events.EventUpdateRequest.duration:type_name -> google.protobuf.Duration
	10, // 2: events.EventWeekListResponse.events:type_name -> events.EventCreateRequest.Event
	10, // 3: events.EventMonthListResponse.events:type_name -> events.EventCreateRequest.Event
	11, // 4: events.EventCreateRequest.Event.duration:type_name -> google.protobuf.Duration
	0,  // 5: events.Events.EventCreate:input_type -> events.EventCreateRequest
	2,  // 6: events.Events.EventUpdate:input_type -> events.EventUpdateRequest
	4,  // 7: events.Events.EventRemove:input_type -> events.EventRemoveRequest
	6,  // 8: events.Events.EventWeekList:input_type -> events.EventWeekListRequest
	8,  // 9: events.Events.EventMonthList:input_type -> events.EventMonthListRequest
	1,  // 10: events.Events.EventCreate:output_type -> events.EventCreateResponse
	3,  // 11: events.Events.EventUpdate:output_type -> events.EventUpdateResponse
	5,  // 12: events.Events.EventRemove:output_type -> events.EventRemoveResponse
	7,  // 13: events.Events.EventWeekList:output_type -> events.EventWeekListResponse
	9,  // 14: events.Events.EventMonthList:output_type -> events.EventMonthListResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_EventService_proto_init() }
func file_api_EventService_proto_init() {
	if File_api_EventService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_EventService_proto_rawDesc), len(file_api_EventService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_EventService_proto_goTypes,
		DependencyIndexes: file_api_EventService_proto_depIdxs,
		MessageInfos:      file_api_EventService_proto_msgTypes,
	}.Build()
	File_api_EventService_proto = out.File
	file_api_EventService_proto_goTypes = nil
	file_api_EventService_proto_depIdxs = nil
}
