// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/UserService.proto

package pb

import (
	_ "github.com/golang/protobuf/ptypes/duration"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCreateRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	User          *UserCreateRequest_User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateRequest) Reset() {
	*x = UserCreateRequest{}
	mi := &file_api_UserService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateRequest) ProtoMessage() {}

func (x *UserCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_UserService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateRequest.ProtoReflect.Descriptor instead.
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_UserService_proto_rawDescGZIP(), []int{0}
}

func (x *UserCreateRequest) GetUser() *UserCreateRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateResponse) Reset() {
	*x = UserCreateResponse{}
	mi := &file_api_UserService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateResponse) ProtoMessage() {}

func (x *UserCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_UserService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateResponse.ProtoReflect.Descriptor instead.
func (*UserCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_UserService_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateRequest) Reset() {
	*x = UserUpdateRequest{}
	mi := &file_api_UserService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateRequest) ProtoMessage() {}

func (x *UserUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_UserService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_UserService_proto_rawDescGZIP(), []int{2}
}

func (x *UserUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserUpdateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateResponse) Reset() {
	*x = UserUpdateResponse{}
	mi := &file_api_UserService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateResponse) ProtoMessage() {}

func (x *UserUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_UserService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateResponse.ProtoReflect.Descriptor instead.
func (*UserUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_UserService_proto_rawDescGZIP(), []int{3}
}

func (x *UserUpdateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRemoveRequest) Reset() {
	*x = UserRemoveRequest{}
	mi := &file_api_UserService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRemoveRequest) ProtoMessage() {}

func (x *UserRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_UserService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRemoveRequest.ProtoReflect.Descriptor instead.
func (*UserRemoveRequest) Descriptor() ([]byte, []int) {
	return file_api_UserService_proto_rawDescGZIP(), []int{4}
}

func (x *UserRemoveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRemoveResponse) Reset() {
	*x = UserRemoveResponse{}
	mi := &file_api_UserService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRemoveResponse) ProtoMessage() {}

func (x *UserRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_UserService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRemoveResponse.ProtoReflect.Descriptor instead.
func (*UserRemoveResponse) Descriptor() ([]byte, []int) {
	return file_api_UserService_proto_rawDescGZIP(), []int{5}
}

func (x *UserRemoveResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserCreateRequest_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateRequest_User) Reset() {
	*x = UserCreateRequest_User{}
	mi := &file_api_UserService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateRequest_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateRequest_User) ProtoMessage() {}

func (x *UserCreateRequest_User) ProtoReflect() protoreflect.Message {
	mi := &file_api_UserService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateRequest_User.ProtoReflect.Descriptor instead.
func (*UserCreateRequest_User) Descriptor() ([]byte, []int) {
	return file_api_UserService_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UserCreateRequest_User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserCreateRequest_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCreateRequest_User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_api_UserService_proto protoreflect.FileDescriptor

const file_api_UserService_proto_rawDesc = "" +
	"\n" +
	"\x15api/UserService.proto\x12\x05users\x1a\x1egoogle/protobuf/duration.proto\"\x94\x01\n" +
	"\x11UserCreateRequest\x121\n" +
	"\x04user\x18\x01 \x01(\v2\x1d.users.UserCreateRequest.UserR\x04user\x1aL\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"$\n" +
	"\x12UserCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"i\n" +
	"\x11UserUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"$\n" +
	"\x12UserUpdateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11UserRemoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12UserRemoveResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xd6\x01\n" +
	"\x05Users\x12C\n" +
	"\n" +
	"UserCreate\x12\x18.users.UserCreateRequest\x1a\x19.users.UserCreateResponse\"\x00\x12C\n" +
	"\n" +
	"UserUpdate\x12\x18.users.UserUpdateRequest\x1a\x19.users.UserUpdateResponse\"\x00\x12C\n" +
	"\n" +
	"UserRemove\x12\x18.users.UserRemoveRequest\x1a\x19.users.UserRemoveResponse\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_api_UserService_proto_rawDescOnce sync.Once
	file_api_UserService_proto_rawDescData []byte
)

func file_api_UserService_proto_rawDescGZIP() []byte {
	file_api_UserService_proto_rawDescOnce.Do(func() {
		file_api_UserService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_UserService_proto_rawDesc), len(file_api_UserService_proto_rawDesc)))
	})
	return file_api_UserService_proto_rawDescData
}

var file_api_UserService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_UserService_proto_goTypes = []any{
	(*UserCreateRequest)(nil),      // 0: users.UserCreateRequest
	(*UserCreateResponse)(nil),     // 1: users.UserCreateResponse
	(*UserUpdateRequest)(nil),      // 2: users.UserUpdateRequest
	(*UserUpdateResponse)(nil),     // 3: users.UserUpdateResponse
	(*UserRemoveRequest)(nil),      // 4: users.UserRemoveRequest
	(*UserRemoveResponse)(nil),     // 5: users.UserRemoveResponse
	(*UserCreateRequest_User)(nil), // 6: users.UserCreateRequest.User
}
var file_api_UserService_proto_depIdxs = []int32{
	6, // 0: users.UserCreateRequest.user:type_name -> users.UserCreateRequest.User
	0, // 1: users.Users.UserCreate:input_type -> users.UserCreateRequest
	2, // 2: users.Users.UserUpdate:input_type -> users.UserUpdateRequest
	4, // 3: users.Users.UserRemove:input_type -> users.UserRemoveRequest
	1, // 4: users.Users.UserCreate:output_type -> users.UserCreateResponse
	3, // 5: users.Users.UserUpdate:output_type -> users.UserUpdateResponse
	5, // 6: users.Users.UserRemove:output_type -> users.UserRemoveResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_UserService_proto_init() }
func file_api_UserService_proto_init() {
	if File_api_UserService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_UserService_proto_rawDesc), len(file_api_UserService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_UserService_proto_goTypes,
		DependencyIndexes: file_api_UserService_proto_depIdxs,
		MessageInfos:      file_api_UserService_proto_msgTypes,
	}.Build()
	File_api_UserService_proto = out.File
	file_api_UserService_proto_goTypes = nil
	file_api_UserService_proto_depIdxs = nil
}
